name: thecommune
favicon: null
layout_spectrum: 0
typography_spectrum: 0.06873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e1e1c'
    - '#dfdbd2'
    - '#b49379'
    - '#715d4b'
    - '#92392e'
  brandStrength: 0.9322754314634949
  lightness: 0.9392338718753308
  saturation: 0.46958595770411193
  rhythmicContrast: 0.6771545789670199
purpose: []
